[ { name: 'Mohawk Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mohawk_Mountain_Ski_Area' },
  { name: 'Mount Southington',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Southington' },
  { name: 'Ski Sundown',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Sundown' },
  { name: 'Woodbury Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Woodbury_Ski_Area' },
  { name: 'Baker Mountain (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Baker_Mountain_(ski_area)' },
  { name: 'Big Rock (ski resort)',
    wikiURL: 'https://en.wikipedia.org/wiki/Big_Rock_(ski_resort)' },
  { name: 'Big Squaw',
    wikiURL: 'https://en.wikipedia.org/wiki/Big_Squaw' },
  { name: 'Black Mountain of Maine',
    wikiURL: 'https://en.wikipedia.org/wiki/Black_Mountain_of_Maine' },
  { name: 'Camden Snow Bowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Camden_Snow_Bowl' },
  { name: 'Eaton Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Eaton_Mountain' },
  { name: 'Lonesome Pine Trails',
    wikiURL: 'https://en.wikipedia.org/wiki/Lonesome_Pine_Trails' },
  { name: 'Lost Valley Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Lost_Valley_Ski_Area' },
  { name: 'Mount Abram (ski resort)',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Abram_(ski_resort)' },
  { name: 'Powderhouse Hill (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Powderhouse_Hill_(ski_area)' },
  { name: 'Saddleback Maine (ski resort)',
    wikiURL: 'https://en.wikipedia.org/wiki/Saddleback_Maine_(ski_resort)' },
  { name: 'Shawnee Peak Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Shawnee_Peak_Ski_Area' },
  { name: 'Sugarloaf (ski resort)',
    wikiURL: 'https://en.wikipedia.org/wiki/Sugarloaf_(ski_resort)' },
  { name: 'Sunday River (Maine)',
    wikiURL: 'https://en.wikipedia.org/wiki/Sunday_River_(Maine)' },
  { name: 'Titcomb Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Titcomb_Mountain' },
  { name: 'Berkshire East Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Berkshire_East_Ski_Resort' },
  { name: 'Blandford Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Blandford_Ski_Area' },
  { name: 'Blue Hills Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Blue_Hills_Ski_Area' },
  { name: 'Bousquet Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Bousquet_Ski_Area' },
  { name: 'Ski Butternut',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Butternut' },
  { name: 'Jiminy Peak (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Jiminy_Peak_(ski_area)' },
  { name: 'Nashoba Valley Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Nashoba_Valley_Ski_Area' },
  { name: 'Ski Bradford',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Bradford' },
  { name: 'Ski Ward',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Ward' },
  { name: 'Wachusett Mountain (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Wachusett_Mountain_(ski_area)' },
  { name: 'Arrowhead Recreation Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Arrowhead_Recreation_Area' },
  { name: 'Attitash',
    wikiURL: 'https://en.wikipedia.org/wiki/Attitash' },
  { name: 'Black Mountain Ski Area (New Hampshire)',
    wikiURL: 'https://en.wikipedia.org/wiki/Black_Mountain_Ski_Area_(New_Hampshire)' },
  { name: 'Bretton Woods Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Bretton_Woods_Mountain_Resort' },
  { name: 'Cannon Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Cannon_Mountain_Ski_Area' },
  { name: 'Cranmore Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Cranmore_Mountain_Resort' },
  { name: 'Crotched Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Crotched_Mountain' },
  { name: 'Dartmouth Skiway',
    wikiURL: 'https://en.wikipedia.org/wiki/Dartmouth_Skiway' },
  { name: 'Granite Gorge Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Granite_Gorge_Ski_Area' },
  { name: 'Gunstock Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Gunstock_Mountain_Resort' },
  { name: 'King Pine',
    wikiURL: 'https://en.wikipedia.org/wiki/King_Pine' },
  { name: 'Loon Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Loon_Mountain' },
  { name: 'McIntyre Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/McIntyre_Ski_Area' },
  { name: 'Mount Sunapee Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Sunapee_Resort' },
  { name: 'Pats Peak',
    wikiURL: 'https://en.wikipedia.org/wiki/Pats_Peak' },
  { name: 'Ragged Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Ragged_Mountain_Resort' },
  { name: 'Tenney Mountain Ski and Snowboarding Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Tenney_Mountain_Ski_and_Snowboarding_Area' },
  { name: 'The Balsams Grand Resort Hotel',
    wikiURL: 'https://en.wikipedia.org/wiki/The_Balsams_Grand_Resort_Hotel' },
  { name: 'Waterville Valley Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Waterville_Valley_Resort' },
  { name: 'Whaleback (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Whaleback_(ski_area)' },
  { name: 'Wildcat Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Wildcat_Mountain_Ski_Area' },
  { name: 'Diamond Hill Reservation',
    wikiURL: 'https://en.wikipedia.org/wiki/Diamond_Hill_Reservation' },
  { name: 'Pine Top Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Pine_Top_Ski_Area' },
  { name: 'Ski Valley',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Valley' },
  { name: 'Yawgoo Valley',
    wikiURL: 'https://en.wikipedia.org/wiki/Yawgoo_Valley' },
  { name: 'Ascutney Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Ascutney_Mountain_Resort' },
  { name: 'Bolton Valley Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Bolton_Valley_Resort' },
  { name: 'Bromley Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Bromley_Mountain' },
  { name: 'Burke Mountain (Vermont)',
    wikiURL: 'https://en.wikipedia.org/wiki/Burke_Mountain_(Vermont)' },
  { name: 'Skiing Cochrans',
    wikiURL: 'https://en.wikipedia.org/wiki/Skiing_Cochrans' },
  { name: 'Jay Peak Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Jay_Peak_Resort' },
  { name: 'Killington Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Killington_Ski_Resort' },
  { name: 'Mad River Glen',
    wikiURL: 'https://en.wikipedia.org/wiki/Mad_River_Glen' },
  { name: 'Magic Mountain, Vermont',
    wikiURL: 'https://en.wikipedia.org/wiki/Magic_Mountain,_Vermont' },
  { name: 'Middlebury College Snow Bowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Middlebury_College_Snow_Bowl' },
  { name: 'Mount Snow',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Snow' },
  { name: 'Okemo Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Okemo_Mountain' },
  { name: 'Pico Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Pico_Mountain' },
  { name: 'Smugglers\' Notch',
    wikiURL: 'https://en.wikipedia.org/wiki/Smugglers%27_Notch' },
  { name: 'Stowe Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Stowe_Mountain_Resort' },
  { name: 'Stratton Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Stratton_Mountain_Resort' },
  { name: 'Sugarbush Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Sugarbush_Resort' },
  { name: 'Suicide Six',
    wikiURL: 'https://en.wikipedia.org/wiki/Suicide_Six' },
  { name: 'Wisp Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Wisp_Ski_Resort' },
  { name: 'Campgaw Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Campgaw_Mountain' },
  { name: 'Hidden Valley (New Jersey)',
    wikiURL: 'https://en.wikipedia.org/wiki/Hidden_Valley_(New_Jersey)' },
  { name: 'Mountain Creek',
    wikiURL: 'https://en.wikipedia.org/wiki/Mountain_Creek' },
  { name: 'Alpine Mountain Ski & Ride Center',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpine_Mountain_Ski_%26_Ride_Center' },
  { name: 'Bear Creek Ski and Recreation Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Bear_Creek_Ski_and_Recreation_Area' },
  { name: 'Blue Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Blue_Mountain_Ski_Area' },
  { name: 'Boyce Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Boyce_Park' },
  { name: 'Camelback Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Camelback_Ski_Area' },
  { name: 'Elk Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Elk_Mountain_Ski_Area' },
  { name: 'Jack Frost Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Jack_Frost_Ski_Resort' },
  { name: 'Liberty Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Liberty_Mountain_Resort' },
  { name: 'Mountain View at Edinboro',
    wikiURL: 'https://en.wikipedia.org/wiki/Mountain_View_at_Edinboro' },
  { name: 'Seven Springs Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Seven_Springs_Mountain_Resort' },
  { name: 'Shawnee Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Shawnee_Mountain_Ski_Area' },
  { name: 'Ski Big Bear',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Big_Bear' },
  { name: 'Montage Mountain Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Montage_Mountain_Ski_Resort' },
  { name: 'Tussey Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Tussey_Mountain_Ski_Area' },
  { name: 'Whitetail Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Whitetail_Ski_Resort' },
  { name: 'Appalachian Ski Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Appalachian_Ski_Mountain' },
  { name: 'Cataloochee Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Cataloochee_Ski_Area' },
  { name: 'Wolf Ridge',
    wikiURL: 'https://en.wikipedia.org/wiki/Wolf_Ridge' },
  { name: 'Ober Gatlinburg',
    wikiURL: 'https://en.wikipedia.org/wiki/Ober_Gatlinburg' },
  { name: 'Massanutten Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Massanutten_Mountain' },
  { name: 'The Homestead (Hot Springs, Virginia)',
    wikiURL: 'https://en.wikipedia.org/wiki/The_Homestead_(Hot_Springs,_Virginia)' },
  { name: 'Wintergreen Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Wintergreen_Resort' },
  { name: 'Canaan Valley Resort State Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Canaan_Valley_Resort_State_Park' },
  { name: 'Snowshoe Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Snowshoe_Mountain' },
  { name: 'Winterplace',
    wikiURL: 'https://en.wikipedia.org/wiki/Winterplace' },
  { name: 'Chestnut Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Chestnut_Mountain' },
  { name: 'Ski Snowstar',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Snowstar' },
  { name: 'Paoli Peaks',
    wikiURL: 'https://en.wikipedia.org/wiki/Paoli_Peaks' },
  { name: 'Perfect North Slopes',
    wikiURL: 'https://en.wikipedia.org/wiki/Perfect_North_Slopes' },
  { name: 'Big Powderhorn Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Big_Powderhorn_Mountain' },
  { name: 'Blackjack Ski Resort (Bessemer, Michigan)',
    wikiURL: 'https://en.wikipedia.org/wiki/Blackjack_Ski_Resort_(Bessemer,_Michigan)' },
  { name: 'Boyne Highlands',
    wikiURL: 'https://en.wikipedia.org/wiki/Boyne_Highlands' },
  { name: 'Boyne Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Boyne_Mountain' },
  { name: 'Caberfae Peaks Ski & Golf Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Caberfae_Peaks_Ski_%26_Golf_Resort' },
  { name: 'Crystal Mountain (Michigan)',
    wikiURL: 'https://en.wikipedia.org/wiki/Crystal_Mountain_(Michigan)' },
  { name: 'Indianhead Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Indianhead_Mountain' },
  { name: 'Marquette Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Marquette_Mountain' },
  { name: 'Mont Ripley',
    wikiURL: 'https://en.wikipedia.org/wiki/Mont_Ripley' },
  { name: 'Mount Bohemia',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Bohemia' },
  { name: 'Mt. Brighton',
    wikiURL: 'https://en.wikipedia.org/wiki/Mt._Brighton' },
  { name: 'Mulligan\'s Hollow Ski Bowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Mulligan%27s_Hollow_Ski_Bowl' },
  { name: 'Nub\'s Nob',
    wikiURL: 'https://en.wikipedia.org/wiki/Nub%27s_Nob' },
  { name: 'Otsego Club & Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Otsego_Club_%26_Resort' },
  { name: 'Pine Knob',
    wikiURL: 'https://en.wikipedia.org/wiki/Pine_Knob' },
  { name: 'Porcupine Mountains',
    wikiURL: 'https://en.wikipedia.org/wiki/Porcupine_Mountains' },
  { name: 'Ski Brule',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Brule' },
  { name: 'Timber Ridge Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Timber_Ridge_Ski_Area' },
  { name: 'Afton Alps',
    wikiURL: 'https://en.wikipedia.org/wiki/Afton_Alps' },
  { name: 'Buck Hill',
    wikiURL: 'https://en.wikipedia.org/wiki/Buck_Hill' },
  { name: 'Hyland Ski and Snowboard Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Hyland_Ski_and_Snowboard_Area' },
  { name: 'Lutsen Mountains',
    wikiURL: 'https://en.wikipedia.org/wiki/Lutsen_Mountains' },
  { name: 'Mount Kato',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Kato' },
  { name: 'Spirit Mountain (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Spirit_Mountain_(ski_area)' },
  { name: 'Welch Village',
    wikiURL: 'https://en.wikipedia.org/wiki/Welch_Village' },
  { name: 'Wild Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Wild_Mountain' },
  { name: 'Hidden Valley Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Hidden_Valley_Ski_Area' },
  { name: 'Snow Creek',
    wikiURL: 'https://en.wikipedia.org/wiki/Snow_Creek' },
  { name: 'Bottineau Winter Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Bottineau_Winter_Park' },
  { name: 'Frost Fire Ski and Snow Board Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Frost_Fire_Ski_and_Snow_Board_Area' },
  { name: 'Huff Hills',
    wikiURL: 'https://en.wikipedia.org/wiki/Huff_Hills' },
  { name: 'Alpine Valley Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpine_Valley_Ski_Area' },
  { name: 'Boston Mills/Brandywine Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Boston_Mills/Brandywine_Ski_Resort' },
  { name: 'Mad River Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Mad_River_Mountain' },
  { name: 'Mystic Miner Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Mystic_Miner_Ski_Resort' },
  { name: 'Great Bear Recreation Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Great_Bear_Recreation_Park' },
  { name: 'Terry Peak',
    wikiURL: 'https://en.wikipedia.org/wiki/Terry_Peak' },
  { name: 'Alpine Valley Resort (Wisconsin)',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpine_Valley_Resort_(Wisconsin)' },
  { name: 'Book Across the Bay',
    wikiURL: 'https://en.wikipedia.org/wiki/Book_Across_the_Bay' },
  { name: 'Cascade Mountain (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Cascade_Mountain_(ski_area)' },
  { name: 'Devils Head Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Devils_Head_Resort' },
  { name: 'Granite Peak Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Granite_Peak_Ski_Area' },
  { name: 'Kettlebowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Kettlebowl' },
  { name: 'Powers Bluff',
    wikiURL: 'https://en.wikipedia.org/wiki/Powers_Bluff' },
  { name: 'Telemark Lodge',
    wikiURL: 'https://en.wikipedia.org/wiki/Telemark_Lodge' },
  { name: 'Trollhaugen',
    wikiURL: 'https://en.wikipedia.org/wiki/Trollhaugen' },
  { name: 'Tyrol Basin',
    wikiURL: 'https://en.wikipedia.org/wiki/Tyrol_Basin' },
  { name: 'Wilmot Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Wilmot_Mountain' },
  { name: 'Arizona Snowbowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Arizona_Snowbowl' },
  { name: 'Elk Ridge Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Elk_Ridge_Ski_Area' },
  { name: 'Mount Lemmon Ski Valley',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Lemmon_Ski_Valley' },
  { name: 'Sunrise Park Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Sunrise_Park_Resort' },
  { name: 'Bald Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Bald_Mountain_Ski_Area' },
  { name: 'Bogus Basin',
    wikiURL: 'https://en.wikipedia.org/wiki/Bogus_Basin' },
  { name: 'Brundage Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Brundage_Mountain' },
  { name: 'Cottonwood Butte',
    wikiURL: 'https://en.wikipedia.org/wiki/Cottonwood_Butte' },
  { name: 'Kelly Canyon',
    wikiURL: 'https://en.wikipedia.org/wiki/Kelly_Canyon' },
  { name: 'Little Ski Hill',
    wikiURL: 'https://en.wikipedia.org/wiki/Little_Ski_Hill' },
  { name: 'Lost Trail Powder Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Lost_Trail_Powder_Mountain' },
  { name: 'Lookout Pass Ski and Recreation Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Lookout_Pass_Ski_and_Recreation_Area' },
  { name: 'Magic Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Magic_Mountain_Resort' },
  { name: 'Pebble Creek, Idaho',
    wikiURL: 'https://en.wikipedia.org/wiki/Pebble_Creek,_Idaho' },
  { name: 'Pomerelle',
    wikiURL: 'https://en.wikipedia.org/wiki/Pomerelle' },
  { name: 'Rotarun Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Rotarun_Ski_Area' },
  { name: 'Schweitzer Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Schweitzer_Mountain' },
  { name: 'Silver Mountain, Idaho',
    wikiURL: 'https://en.wikipedia.org/wiki/Silver_Mountain,_Idaho' },
  { name: 'Snowhaven',
    wikiURL: 'https://en.wikipedia.org/wiki/Snowhaven' },
  { name: 'Soldier Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Soldier_Mountain' },
  { name: 'Bald Mountain (Idaho)',
    wikiURL: 'https://en.wikipedia.org/wiki/Bald_Mountain_(Idaho)' },
  { name: 'Tamarack Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Tamarack_Resort' },
  { name: 'Big Sky Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Big_Sky_Ski_Resort' },
  { name: 'Blacktail Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Blacktail_Mountain_Ski_Area' },
  { name: 'Bridger Bowl Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Bridger_Bowl_Ski_Area' },
  { name: 'Discovery Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Discovery_Ski_Area' },
  { name: 'Great Divide Snowsports',
    wikiURL: 'https://en.wikipedia.org/wiki/Great_Divide_Snowsports' },
  { name: 'Lost Trail Powder Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Lost_Trail_Powder_Mountain' },
  { name: 'Maverick Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Maverick_Mountain_Ski_Area' },
  { name: 'Montana Snowbowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Montana_Snowbowl' },
  { name: 'Moonlight Basin',
    wikiURL: 'https://en.wikipedia.org/wiki/Moonlight_Basin' },
  { name: 'Red Lodge Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Red_Lodge_Mountain_Resort' },
  { name: 'Showdown Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Showdown_Ski_Area' },
  { name: 'Teton Pass Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Teton_Pass_Ski_Area' },
  { name: 'Turner Mountain Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Turner_Mountain_Ski_Resort' },
  { name: 'The Big Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/The_Big_Mountain' },
  { name: 'Yellowstone Club',
    wikiURL: 'https://en.wikipedia.org/wiki/Yellowstone_Club' },
  { name: 'Angel Fire Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Angel_Fire_Resort' },
  { name: 'Pajarito Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Pajarito_Mountain_Ski_Area' },
  { name: 'Ski Apache',
    wikiURL: 'https://en.wikipedia.org/wiki/Ski_Apache' },
  { name: 'Sipapu (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Sipapu_(ski_area)' },
  { name: 'Taos Ski Valley, New Mexico',
    wikiURL: 'https://en.wikipedia.org/wiki/Taos_Ski_Valley,_New_Mexico' },
  { name: 'Sandia Peak Tramway',
    wikiURL: 'https://en.wikipedia.org/wiki/Sandia_Peak_Tramway' },
  { name: 'Alta Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Alta_Ski_Area' },
  { name: 'Beaver Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Beaver_Mountain' },
  { name: 'Brian Head Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Brian_Head_Ski_Resort' },
  { name: 'Brighton Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Brighton_Ski_Resort' },
  { name: 'Canyons Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Canyons_Resort' },
  { name: 'Deer Valley Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Deer_Valley_Resort' },
  { name: 'Park City Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Park_City_Mountain_Resort' },
  { name: 'Powder Mountain Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Powder_Mountain_Ski_Resort' },
  { name: 'Snowbasin',
    wikiURL: 'https://en.wikipedia.org/wiki/Snowbasin' },
  { name: 'Snowbird ski resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Snowbird_ski_resort' },
  { name: 'Solitude Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Solitude_Mountain_Resort' },
  { name: 'Sundance Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Sundance_Ski_Resort' },
  { name: 'Wolf Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/Wolf_Mountain' },
  { name: 'Beartooth Pass',
    wikiURL: 'https://en.wikipedia.org/wiki/Beartooth_Pass' },
  { name: 'Grand Targhee Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Grand_Targhee_Resort' },
  { name: 'Hogadon Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Hogadon_Ski_Area' },
  { name: 'Jackson Hole Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Jackson_Hole_Mountain_Resort' },
  { name: 'Pine Creek Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Pine_Creek_Ski_Area' },
  { name: 'Snow King',
    wikiURL: 'https://en.wikipedia.org/wiki/Snow_King' },
  { name: 'Snowy Range Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Snowy_Range_Ski_Area' },
  { name: 'White Pine Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/White_Pine_Ski_Resort' },
  { name: 'Alpenglow at Arctic Valley',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpenglow_at_Arctic_Valley' },
  { name: 'Alyeska Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Alyeska_Resort' },
  { name: 'Eaglecrest Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Eaglecrest_Ski_Area' },
  { name: 'Hilltop Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Hilltop_Ski_Area' },
  { name: 'Moose Mountain (Alaska)',
    wikiURL: 'https://en.wikipedia.org/wiki/Moose_Mountain_(Alaska)' },
  { name: 'Mount Eyak',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Eyak' },
  { name: 'Skiland',
    wikiURL: 'https://en.wikipedia.org/wiki/Skiland' },
  { name: 'Mount Shasta Ski Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Shasta_Ski_Park' },
  { name: 'Alpine Meadows, California',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpine_Meadows,_California' },
  { name: 'Boreal Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Boreal_Mountain_Resort' },
  { name: 'Donner Ski Ranch',
    wikiURL: 'https://en.wikipedia.org/wiki/Donner_Ski_Ranch' },
  { name: 'Granlibakken',
    wikiURL: 'https://en.wikipedia.org/wiki/Granlibakken' },
  { name: 'Heavenly Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Heavenly_Ski_Resort' },
  { name: 'Homewood Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Homewood_Mountain_Resort' },
  { name: 'Kirkwood Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Kirkwood_Mountain_Resort' },
  { name: 'Northstar at Tahoe',
    wikiURL: 'https://en.wikipedia.org/wiki/Northstar_at_Tahoe' },
  { name: 'Sierra-at-Tahoe',
    wikiURL: 'https://en.wikipedia.org/wiki/Sierra-at-Tahoe' },
  { name: 'Squaw Valley Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Squaw_Valley_Ski_Resort' },
  { name: 'Sugar Bowl Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Sugar_Bowl_Ski_Resort' },
  { name: 'Tahoe Donner Downhill Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Tahoe_Donner_Downhill_Ski_Area' },
  { name: 'Badger Pass Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Badger_Pass_Ski_Area' },
  { name: 'Bear Valley (resort)',
    wikiURL: 'https://en.wikipedia.org/wiki/Bear_Valley_(resort)' },
  { name: 'Dodge Ridge Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Dodge_Ridge_Ski_Area' },
  { name: 'June Mountain',
    wikiURL: 'https://en.wikipedia.org/wiki/June_Mountain' },
  { name: 'Mammoth Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mammoth_Mountain_Ski_Area' },
  { name: 'China Peak',
    wikiURL: 'https://en.wikipedia.org/wiki/China_Peak' },
  { name: 'Alta Sierra Ski Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Alta_Sierra_Ski_Resort' },
  { name: 'Buckhorn Ski and Snowboard Club',
    wikiURL: 'https://en.wikipedia.org/wiki/Buckhorn_Ski_and_Snowboard_Club' },
  { name: 'Bear Mountain (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Bear_Mountain_(ski_area)' },
  { name: 'Kratka Ridge',
    wikiURL: 'https://en.wikipedia.org/wiki/Kratka_Ridge' },
  { name: 'Mount Baldy Ski Lifts',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Baldy_Ski_Lifts' },
  { name: 'Mount Waterman',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Waterman' },
  { name: 'Mountain High',
    wikiURL: 'https://en.wikipedia.org/wiki/Mountain_High' },
  { name: 'Snow Summit',
    wikiURL: 'https://en.wikipedia.org/wiki/Snow_Summit' },
  { name: 'Snow Valley Mountain Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Snow_Valley_Mountain_Resort' },
  { name: 'Diamond Peak (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Diamond_Peak_(ski_area)' },
  { name: 'Las Vegas Ski & Snowboard Resort',
    wikiURL: 'https://en.wikipedia.org/wiki/Las_Vegas_Ski_%26_Snowboard_Resort' },
  { name: 'Mount Rose Ski Tahoe',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Rose_Ski_Tahoe' },
  { name: 'Cooper Spur ski area',
    wikiURL: 'https://en.wikipedia.org/wiki/Cooper_Spur_ski_area' },
  { name: 'Mount Hood Meadows',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Hood_Meadows' },
  { name: 'Mount Hood Ski Bowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Hood_Ski_Bowl' },
  { name: 'Summit Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Summit_Ski_Area' },
  { name: 'Timberline Lodge ski area',
    wikiURL: 'https://en.wikipedia.org/wiki/Timberline_Lodge_ski_area' },
  { name: 'Hoodoo (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Hoodoo_(ski_area)' },
  { name: 'Mt. Bachelor ski area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mt._Bachelor_ski_area' },
  { name: 'Willamette Pass ski area',
    wikiURL: 'https://en.wikipedia.org/wiki/Willamette_Pass_ski_area' },
  { name: 'Anthony Lakes (ski area)',
    wikiURL: 'https://en.wikipedia.org/wiki/Anthony_Lakes_(ski_area)' },
  { name: 'Ferguson Ridge',
    wikiURL: 'https://en.wikipedia.org/wiki/Ferguson_Ridge' },
  { name: 'Mount Ashland Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Ashland_Ski_Area' },
  { name: 'Spout Springs',
    wikiURL: 'https://en.wikipedia.org/wiki/Spout_Springs' },
  { name: 'Warner Canyon',
    wikiURL: 'https://en.wikipedia.org/wiki/Warner_Canyon' },
  { name: '49 Degrees North Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/49_Degrees_North_Ski_Area' },
  { name: 'Badger Mountain Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Badger_Mountain_Ski_Area' },
  { name: 'Bluewood Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Bluewood_Ski_Area' },
  { name: 'Crystal Mountain (Washington)',
    wikiURL: 'https://en.wikipedia.org/wiki/Crystal_Mountain_(Washington)' },
  { name: 'Echo Valley Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Echo_Valley_Ski_Area' },
  { name: 'Hurricane Ridge Ski and Snowboard Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Hurricane_Ridge_Ski_and_Snowboard_Area' },
  { name: 'Leavenworth Ski Hill',
    wikiURL: 'https://en.wikipedia.org/wiki/Leavenworth_Ski_Hill' },
  { name: 'Loup Loup Ski Bowl',
    wikiURL: 'https://en.wikipedia.org/wiki/Loup_Loup_Ski_Bowl' },
  { name: 'Meany Lodge',
    wikiURL: 'https://en.wikipedia.org/wiki/Meany_Lodge' },
  { name: 'Mission Ridge Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mission_Ridge_Ski_Area' },
  { name: 'Mount Baker Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Baker_Ski_Area' },
  { name: 'Mount Spokane Ski and Snowboard Park',
    wikiURL: 'https://en.wikipedia.org/wiki/Mount_Spokane_Ski_and_Snowboard_Park' },
  { name: 'Stevens Pass Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/Stevens_Pass_Ski_Area' },
  { name: 'The Summit at Snoqualmie',
    wikiURL: 'https://en.wikipedia.org/wiki/The_Summit_at_Snoqualmie' },
  { name: 'Alpental',
    wikiURL: 'https://en.wikipedia.org/wiki/Alpental' },
  { name: 'White Pass Ski Area',
    wikiURL: 'https://en.wikipedia.org/wiki/White_Pass_Ski_Area' } ]
